---
name: your_work_projects_vue
feature_issue_url: https://gitlab.com/groups/gitlab-org/-/epics/13066
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/155472
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/465889
milestone: '17.1'
type: wip
group: group::tenant scale
default_enabled: false
