---
name: ci_expand_variables_in_compare_to
feature_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/369916
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/157147
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/466374
milestone: '17.2'
group: group::pipeline security
type: gitlab_com_derisk
default_enabled: false
