---
description: Counts VSA (both group- and project-level) views
internal_events: true
action: view_cycle_analytics
identifiers:
- project
- namespace
- user
product_group: optimize
milestone: '17.0'
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/149947
distributions:
- ce
- ee
tiers:
- free
- premium
- ultimate
