---
name: duo_chat_requires_licensed_seat
feature_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/457090
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/150072
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/457091
milestone: '17.0'
group: group::duo chat
type: beta
default_enabled: false
